=== voteaire/voteaire-ballot-counter/src/model/json_schemas/ballot_proposal.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title": "BallotProposal",
  "type": "object",
  "properties": {
    "ObjectType": {
      "enum": ["BallotProposal"],
      "purpose": "Identify the type of object this is",
      "example": "BallotProposal"
    },
    "ObjectVersion": {
      "enum": ["1.0.0"],
      "purpose": "Specify the version of the object for future reference and parsing"
    },
    "NetworkId": {
      "type": "string",
      "maxLength": 64,
      "purpose": "Identify the voting 'network' this proposal belongs to",
      "example": "Voteaire"
    },
    "ProposalId": {
      "type": "string",
      "maxLength": 64,
      "purpose": "Unique identifier (hash?) identifying this particular proposal",
      "example": "52da18fb-64ec-4d00-9484-fdb0b67ef678",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "ProposalURL": {
      "type": "string",
      "maxLength": 64,
      "purpose": "Provide a URL where more information about the proposal may live (maybe a forum for discussing pros and cons, etc)",
      "example": "https://example.com"
    },
    "BallotType": {
      "$ref": "ballot_type.json"
    },
    "Title": {
      "type": "string",
      "maxLength": 64,
      "purpose": "The title of the ballot proposal",
      "example": "Pineapple on pizza?"
    },
    "Description": {
      "type": "array",
      "purpose": "Provide more information about this proposal including any references",
      "items": {
          "type": "string",
          "maxLength": 64,
          "purpose": "Description text broken into 64-character strings to accomodate the maximum string length"
      },
      "example": "<LONG DESCRIPTION>"
    },
    "Questions": {
      "type": "array",
      "purpose": "Provide one or more ballot questions that voters will vote on.",
      "minItems": 1,
      "items": {
        "$ref": "ballot_question.json"
      }
    },
    "VoteStartEpoch": {
      "type": "integer",
      "purpose": "Specify the Epoch that voting will start. Voting will be enabled at the beginning of this epoch.",
      "example": 213
    },
    "VoteEndEpoch": {
      "type": "integer",
      "purpose": "Specify the Epoch that voting will end. Voting will be enabled until the end of this epoch.",
      "example": 215
    },
    "SnapshotEpoch": {
      "type": "integer",
      "purpose": "Define which epoch snapshot will be used for weighting voting power.",
      "example": 247,
      "default": 0
    }
  },
  "required":[
    "ObjectType",
    "ObjectVersion",
    "NetworkId",
    "ProposalId",
    "BallotType",
    "Title",
    "Questions",
    "VoteStartEpoch",
    "VoteEndEpoch",
    "SnapshotEpoch"
  ]
}

=== voteaire/voteaire-ballot-counter/tests/unit/fixtures/schema_samples/proposal1.json
{
  "ObjectType": "BallotProposal",
  "ObjectVersion": "1.0.0",
  "NetworkId": "Voteaire",
  "ProposalId": "52da18fb-64ec-4d00-9484-fdb0b67ef678",
  "ProposalURL": "https://canucks-publishing.com",
  "BallotType": {
    "Name": "Simple"
  },
  "Title": "Pineapple on pizza?",
  "Questions": [
    {
      "QuestionId": "36f06c15-5a2d-4c7c-bf56-ffb2affb8320",
      "Question": [
        "Do you think people should be allowed to put pineapple on pizza?"
      ],
      "Description": [
        "People have been putting odd things on pizza for centuries, however ",
        "pineapple is a particularly polarizing topping."
      ],
      "ChoiceLimit": 1,
      "Choices": [
        {
          "ChoiceId": "c17d31d5-3bea-41b9-91fc-e9adba00daee",
          "Name": "Hell yeah, pineapple is great!",
          "Description": []
        },
        {
          "ChoiceId": "b0fbc41a-13ff-415f-8516-defef00b6980",
          "Name": "Are you crazy? No way!",
          "Description": []
        }
      ]
    }
  ],
  "VoteStartEpoch": 329,
  "VoteEndEpoch": 329,
  "SnapshotEpoch": 328
}
